// <auto-generated />
namespace CardsAndDecks.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class NumberOfAssignments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NumberOfAssignments));
        
        string IMigrationMetadata.Id
        {
            get { return "202010140553311_NumberOfAssignments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
